<a href="https://colab.research.google.com/github/VidhiNegi19/sem4/blob/main/12_N2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
#np.transpose()
#Create a 2d array
two_d_array = np.array(np.random.randint(1,5,(2,5)))
print(f"the defined array is\n{two_d_array}")
print(f"\n the shape of the array is {two_d_array.shape}")

the defined array is
[[2 3 3 1 4]
 [4 3 4 1 2]]

 the shape of the array is (2, 5)


In [3]:
#Storing the transpose in another matrix object
another_two_d_array = np.transpose(two_d_array)
print(f" the transpose of the array is \n{another_two_d_array}")
print(f"\n the shape of the array is {another_two_d_array.shape}")


 the transpose of the array is 
[[2 4]
 [3 3]
 [3 4]
 [1 1]
 [4 2]]

 the shape of the array is (5, 2)


In [4]:
#Creating a 3d array
three_d_array = np.array(np.random.randint(1,6,(3,3,3)))
print(f"the defined array is\n{three_d_array}")
print(f"\n the shape of the array is {three_d_array.shape}")

the defined array is
[[[5 5 5]
  [1 4 3]
  [1 3 2]]

 [[2 1 2]
  [2 1 1]
  [4 5 5]]

 [[3 1 3]
  [1 5 3]
  [1 5 1]]]

 the shape of the array is (3, 3, 3)


In [5]:
#Storing the transpose of the created array
another_three_d_array = np.transpose(three_d_array)
print(f"the transpose the array is \n{three_d_array}")
print(f"\n the shape of the array is \n{another_three_d_array.shape}")

the transpose the array is 
[[[5 5 5]
  [1 4 3]
  [1 3 2]]

 [[2 1 2]
  [2 1 1]
  [4 5 5]]

 [[3 1 3]
  [1 5 3]
  [1 5 1]]]

 the shape of the array is 
(3, 3, 3)


In [6]:
#np.reshape()
random_two_d_array = np.array(np.random.randint(2,4,(2,6)))
print(f" the defined array is \n{random_two_d_array}")
print(f"\n the shape of the array is{random_two_d_array.shape}")

 the defined array is 
[[2 3 3 3 3 3]
 [2 2 2 3 2 3]]

 the shape of the array is(2, 6)


In [7]:
#Now we can reshape this to 1d,2d,3d array
new_shape = (2,2,3)
reshaped_random_two_d_array = np.reshape(random_two_d_array, new_shape)
print(f" the reshaped array is \n{reshaped_random_two_d_array}")
print(f"\n the shape of the array is{reshaped_random_two_d_array.shape}")


 the reshaped array is 
[[[2 3 3]
  [3 3 3]]

 [[2 2 2]
  [3 2 3]]]

 the shape of the array is(2, 2, 3)


In [8]:
new_shape = (3,2,2)
reshaped_random_two_d_array = np.reshape(random_two_d_array, new_shape)
print(f" the reshaped array is \n{reshaped_random_two_d_array}")
print(f" \n the shape of the array is{reshaped_random_two_d_array.shape}")

 the reshaped array is 
[[[2 3]
  [3 3]]

 [[3 3]
  [2 2]]

 [[2 3]
  [2 3]]]
 
 the shape of the array is(3, 2, 2)


In [9]:
#Create a 3d array
random_3d_array = np.array(np.random.randint(1,5,(3,3,2)))
print(f"the defined array is\n{random_3d_array}")
print(f"\n the shape of the array is {random_3d_array.shape}")

the defined array is
[[[3 4]
  [2 1]
  [2 1]]

 [[2 4]
  [4 4]
  [2 4]]

 [[1 3]
  [1 2]
  [3 1]]]

 the shape of the array is (3, 3, 2)


In [10]:
#Reshape the created 3d array
new_shape = (3,2,3)
reshaped_random_3d_array = np.reshape(random_3d_array, new_shape)
print(f" the reshaped array is \n{reshaped_random_3d_array}")
print("f\n the shape of the array is {reshaped_random_3d_array.shape}")

 the reshaped array is 
[[[3 4 2]
  [1 2 1]]

 [[2 4 4]
  [4 2 4]]

 [[1 3 1]
  [2 3 1]]]
f
 the shape of the array is {reshaped_random_3d_array.shape}


In [11]:
#np.resize(shape)
#Initialize a 3d array
random_3d_array = np.array(np.random.randint(1,5,(3,3,2)))
print(f"the defined array is\n{random_3d_array}")
print(f"\n the shape of the array is {random_3d_array.shape}")

the defined array is
[[[2 1]
  [1 1]
  [3 2]]

 [[4 3]
  [2 3]
  [2 3]]

 [[2 4]
  [2 3]
  [1 2]]]

 the shape of the array is (3, 3, 2)


In [12]:
#Resize the created 3d array
new_shape = (3,2,3)
resized_random_3d_array = np.resize(random_3d_array, new_shape)
print(f" the resized array is \n{resized_random_3d_array}")
print(f" \n the shape of the array is {reshaped_random_3d_array.shape}")

 the resized array is 
[[[2 1 1]
  [1 3 2]]

 [[4 3 2]
  [3 2 3]]

 [[2 4 2]
  [3 1 2]]]
 
 the shape of the array is (3, 2, 3)


In [13]:
random_3d_array.resize(new_shape)
random_3d_array

array([[[2, 1, 1],
        [1, 3, 2]],

       [[4, 3, 2],
        [3, 2, 3]],

       [[2, 4, 2],
        [3, 1, 2]]])

In [14]:
#np.flatten()
#Initialize a 3d array
random_3d_array = np.array(np.random.randint(1,5,(3,3,2)))
print(f"the defined array is\n{random_3d_array}")
print(f"\n the shape of the array is {random_3d_array.shape}")

the defined array is
[[[4 3]
  [4 2]
  [2 1]]

 [[3 3]
  [1 2]
  [4 2]]

 [[2 3]
  [3 2]
  [3 4]]]

 the shape of the array is (3, 3, 2)


In [15]:
#Flatten the 3d array
random_3d_array.flatten()

array([4, 3, 4, 2, 2, 1, 3, 3, 1, 2, 4, 2, 2, 3, 3, 2, 3, 4])

In [16]:
#Flattens the array in row-major order with 'c'
random_3d_array.flatten('c')

array([4, 3, 4, 2, 2, 1, 3, 3, 1, 2, 4, 2, 2, 3, 3, 2, 3, 4])

In [17]:
random_3d_array.flatten('f')

array([4, 3, 2, 4, 1, 3, 2, 4, 3, 3, 3, 3, 2, 2, 2, 1, 2, 4])

In [18]:
#np.insert(arr,obj,values,axis)
import numpy as np

a = np.random.randint(10,20,(2,3,4))
print(a)
print(a.shape)

[[[16 13 14 10]
  [15 13 17 18]
  [15 18 17 16]]

 [[10 17 14 12]
  [17 11 15 19]
  [14 16 15 18]]]
(2, 3, 4)


In [19]:
#Insert along axis=0
np.insert(a,1,100,axis=0)

array([[[ 16,  13,  14,  10],
        [ 15,  13,  17,  18],
        [ 15,  18,  17,  16]],

       [[100, 100, 100, 100],
        [100, 100, 100, 100],
        [100, 100, 100, 100]],

       [[ 10,  17,  14,  12],
        [ 17,  11,  15,  19],
        [ 14,  16,  15,  18]]])

In [20]:
#Along axis=1
np.insert(a,0,50,axis=1)

array([[[50, 50, 50, 50],
        [16, 13, 14, 10],
        [15, 13, 17, 18],
        [15, 18, 17, 16]],

       [[50, 50, 50, 50],
        [10, 17, 14, 12],
        [17, 11, 15, 19],
        [14, 16, 15, 18]]])

In [21]:
#Along axis=2
np.insert(a,0,200,axis=2)

array([[[200,  16,  13,  14,  10],
        [200,  15,  13,  17,  18],
        [200,  15,  18,  17,  16]],

       [[200,  10,  17,  14,  12],
        [200,  17,  11,  15,  19],
        [200,  14,  16,  15,  18]]])

In [22]:
#np.append(arr,values,axis)

a = np.random.randint(2,6,(2,3,3))
print(a)
print(a.shape)

[[[4 2 5]
  [2 2 3]
  [2 4 4]]

 [[5 5 5]
  [2 5 5]
  [4 5 2]]]
(2, 3, 3)


In [23]:
#Append a value to the array. It flattens the array and append =99 to the end
np.append(a,50)

array([ 4,  2,  5,  2,  2,  3,  2,  4,  4,  5,  5,  5,  2,  5,  5,  4,  5,
        2, 50])

In [24]:
#Fix the axis other than axis of appending
b = np.random.randint(2,6,(2,1,3))
print(b)

[[[5 3 2]]

 [[4 4 3]]]


In [25]:
print(a)
print(a.shape)

[[[4 2 5]
  [2 2 3]
  [2 4 4]]

 [[5 5 5]
  [2 5 5]
  [4 5 2]]]
(2, 3, 3)


In [26]:
np.append(a,b,axis=1)

array([[[4, 2, 5],
        [2, 2, 3],
        [2, 4, 4],
        [5, 3, 2]],

       [[5, 5, 5],
        [2, 5, 5],
        [4, 5, 2],
        [4, 4, 3]]])

In [27]:
#np.delete(arr,pbj,axis)

a = np.random.randint(2,6,(2,3,3))
print(a)
print(a.shape)

[[[2 2 3]
  [2 2 2]
  [3 5 5]]

 [[5 4 4]
  [5 2 2]
  [2 3 2]]]
(2, 3, 3)


In [28]:
#Delete along axis=0
np.delete(a,(0), axis=0)

array([[[5, 4, 4],
        [5, 2, 2],
        [2, 3, 2]]])

In [29]:
#Delete along axis=1
np.delete(a,(0,2), axis=1)


array([[[2, 2, 2]],

       [[5, 2, 2]]])

In [30]:
a

array([[[2, 2, 3],
        [2, 2, 2],
        [3, 5, 5]],

       [[5, 4, 4],
        [5, 2, 2],
        [2, 3, 2]]])

In [31]:
#Delete along axis=2
np.delete(a,(0,1), axis=2)

array([[[3],
        [2],
        [5]],

       [[4],
        [2],
        [2]]])

In [32]:
#np.unique(arr,return_index,return_inverse,return_counts)
#Initialized array

a= np.random.randint(2,20,(2,3,3))
print(a)
print(a.shape)

[[[19 14 19]
  [10 14  7]
  [ 8 11  6]]

 [[ 9 18 11]
  [ 8  3 19]
  [13  2  8]]]
(2, 3, 3)


In [33]:
np.unique(a)

array([ 2,  3,  6,  7,  8,  9, 10, 11, 13, 14, 18, 19])

In [34]:
#Return_counts = True
np.unique(a,return_counts=True)

(array([ 2,  3,  6,  7,  8,  9, 10, 11, 13, 14, 18, 19]),
 array([1, 1, 1, 1, 3, 1, 1, 2, 1, 2, 1, 3]))

In [35]:
#Return_index = True
np.unique(a,return_counts = True, return_index = True)

(array([ 2,  3,  6,  7,  8,  9, 10, 11, 13, 14, 18, 19]),
 array([16, 13,  8,  5,  6,  9,  3,  7, 15,  1, 10,  0]),
 array([1, 1, 1, 1, 3, 1, 1, 2, 1, 2, 1, 3]))

In [36]:
#Lets take an example of a list

a = [1,2,3]
b=a
b[0] = 10
print(b)
print(a)

[10, 2, 3]
[10, 2, 3]


In [37]:
#Lets use the copy method
a=[1,2,3]
b=a.copy()
b[0] = 10
print(b)
print(a)

[10, 2, 3]
[1, 2, 3]


In [38]:
#Let us look at an array
a = np.array([2,34,12])
b=a
b[0] = -999
print(b)
print(a)

[-999   34   12]
[-999   34   12]


In [39]:
a = np.array([2,34,12])
b=a.copy()
b[0] = -999
print(b)
print(a)

[-999   34   12]
[ 2 34 12]


In [ ]:
#Basic operations and functions
np.arange(3)

In [40]:
np.arange(3) + 5

array([5, 6, 7])

In [41]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [42]:
np.ones((3,3)) + np.arange(3)

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [43]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [44]:
np.ones((2,4)) + np.arange(4)

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [45]:
np.arange(3).reshape((3,1))

array([[0],
       [1],
       [2]])

In [46]:
np.arange(3).reshape((3,1)) + np.arange(3)

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [47]:
np.arange(3).reshape((3,1)) + np.arange(4)

array([[0, 1, 2, 3],
       [1, 2, 3, 4],
       [2, 3, 4, 5]])

In [48]:
np.arange(2)

array([0, 1])

In [49]:
a = np.random.randint(2,6,(2,4))
print(a)
b = np.random.randint(1,10,(2,2))
print(b)

[[3 2 2 3]
 [2 5 3 2]]
[[9 4]
 [1 4]]


In [50]:
a = np.random.randint(2,6,(2,4))
print(a)
b = np.random.randint(1,10,(2,2))
print(b)

[[2 4 3 4]
 [2 4 2 4]]
[[5 4]
 [7 1]]


In [53]:
# Multiply the first two columns of `a` with `b`
result = np.multiply(a[:, :2], b)
print(result)
print(result.shape)  # Output shape will be (2, 2)

[[10 16]
 [14  4]]
(2, 2)


In [62]:
#Dividing the first two columns of `a` with `b`
result = np.divide(a[:, :2], b)
print(result)
print(result.shape)  # Output shape will be (2, 2)

ValueError: operands could not be broadcast together with shapes (3,2) (2,2) 

In [54]:
#Some aggregations operations

a = np.random.randint(5,9,(2,4))
print(a)

[[6 6 7 8]
 [5 5 5 5]]


In [55]:
print(np.sum(a))
print(np.sum(a,axis=0))
print(np.sum(a,axis=1))


47
[11 11 12 13]
[27 20]


In [56]:
#Calculate minimum
print(np.min(a))
print(np.min(a,axis=1))

5
[6 5]


In [57]:
#Sort the array
a = np.random.randint(0,20,(3,3))
print(a)

[[15  7  3]
 [ 6 14  8]
 [ 4 19 19]]


In [58]:
#Ascending columns
print(np.sort(a,axis=0))

[[ 4  7  3]
 [ 6 14  8]
 [15 19 19]]


In [59]:
#Ascending rows
print(np.sort(a,axis=1))

[[ 3  7 15]
 [ 6  8 14]
 [ 4 19 19]]


In [60]:
#Descending
print(-np.sort(-a,axis=1))

[[15  7  3]
 [14  8  6]
 [19 19  4]]


In [61]:
sum(np.arange(3)*np.arange(3).transpose())

5